#!/usr/bin/env node
/* admin-reset — operator CLI for the clients table.

   Usage (also via `pnpm admin:reset -- --help`):
     node scripts/admin-reset.js --reset admin
     node scripts/admin-reset.js --create --id tenant-acme --rpm 300

   The script NEVER opens the database. It prints:
     • a plaintext API key (save it NOW — never shown again), and
     • an SQL statement the operator pastes into sqlite3.

   Generated by Claude as part of Phase 5.6 (operator escape hatch). The
   pure logic lives in src/admin/admin-reset-cli.ts + spec; this file
   is the runtime entry point so operators can run the script via a
   stable path even after the project's source layout evolves. */

const cli = require('../dist/admin/admin-reset-cli');

const result = cli.main(process.argv.slice(2));
if (result !== undefined) {
    process.stdout.write(result);
    if (!result.endsWith('\n')) process.stdout.write('\n');
}
